---
- name: Lookup to the NEOW Web Service
  hosts: localhost
  gather_facts: false
    #vars:
    #  api_key: "{{ api_key }}"
    #  today: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    #  one_week_ago: "{{ lookup('pipe', 'date -d\"1 week ago\" +%Y-%m-%d') }}"

  collections:
    - rzfeeser.nasa_apis

  roles:
    - nasa-neows-info-file-creator
