---
- name: Invoke NASA API
  hosts: localhost
  gather_facts: False

  collections:
    - rzfeeser.nasa_apis

    # vars:
    #   start_date: "{{ start_date }}"
    #   end_date: "{{ end_date }}"
    #   api_key: "{{ api_key }}"
    #   version: "{{ version }}"

  roles:
    - nasa-neows-info 
